<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                "title" => "Wraith Badge",
                "slug" => "wraith-black-badge",
                "brand_id" => 1,
                "price" => 545.0,
                "year" => 2019,
                "color" => "Black",
                "zeroToHundred" => 4.6,
                "transmission" => "Automatic",
                "engine" => "6.6L V12 twin turbo",
                "maxSpeed" => 250,
                "horsepower" => 624,
                "seats" => 4,
                "fuelType" => "Petrol",
                "body_type_id" => 1,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "X6",
                "slug" => "bmw-x6",
                "brand_id" => 2,
                "price" => 219.0,
                "year" => 2023,
                "color" => "White",
                "zeroToHundred" => 5.1,
                "transmission" => "Automatic",
                "engine" => "3L V6",
                "maxSpeed" => 250,
                "horsepower" => 567,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "X7 M50i",
                "slug" => "bmw-x7-m50i",
                "brand_id" => 2,
                "price" => 258.0,
                "year" => 2021,
                "color" => "White",
                "zeroToHundred" => 4.7,
                "transmission" => "Automatic",
                "engine" => "4.4",
                "maxSpeed" => 300,
                "horsepower" => 523,
                "seats" => 6,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "RSQ8",
                "slug" => "rsq8",
                "brand_id" => 3,
                "price" => 322.0,
                "year" => 2023,
                "color" => "Black",
                "zeroToHundred" => 3.8,
                "transmission" => "Automatic",
                "engine" => "4.0-liter V-8",
                "maxSpeed" => 250,
                "horsepower" => 591,
                "seats" => 4,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Tahoe",
                "slug" => "chevrolet-tahoe",
                "brand_id" => 4,
                "price" => 129.0,
                "year" => 2021,
                "color" => "Blue",
                "zeroToHundred" => 9.5,
                "transmission" => "Automatic",
                "engine" => "5.3L V8",
                "maxSpeed" => 172,
                "horsepower" => 355,
                "seats" => 8,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 6,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Huracan Spyder",
                "slug" => "lamborghini-huracan",
                "brand_id" => 7,
                "price" => 748.0,
                "year" => 2021,
                "color" => "Yellow",
                "zeroToHundred" => 3.2,
                "transmission" => "Automatic",
                "engine" => "5.2L V10 Naturally aspirated",
                "maxSpeed" => 325,
                "horsepower" => 580,
                "seats" => 2,
                "fuelType" => "Petrol",
                "body_type_id" => 7,
                "category_id" => 7,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "R8 V10 Spyder",
                "slug" => "audi-r8",
                "brand_id" => 3,
                "price" => 464.0,
                "year" => 2021,
                "color" => "Black",
                "zeroToHundred" => 3.3,
                "transmission" => "Automatic",
                "engine" => "5.2L V10 twin-turbo",
                "maxSpeed" => 320,
                "horsepower" => 540,
                "seats" => 2,
                "fuelType" => "Petrol",
                "body_type_id" => 7,
                "category_id" => 7,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Urus",
                "slug" => "lamborghini-urus",
                "brand_id" => 7,
                "price" => 696.0,
                "year" => 2020,
                "color" => "Red",
                "zeroToHundred" => 3.6,
                "transmission" => "Automatic",
                "engine" => "4.0L V8 twin-turbocharged",
                "maxSpeed" => 304,
                "horsepower" => 650,
                "seats" => 4,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 7,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Corvette Spyder",
                "slug" => "chevrolet-corvette",
                "brand_id" => 4,
                "price" => 412.0,
                "year" => 2021,
                "color" => "Grey",
                "zeroToHundred" => 4.0,
                "transmission" => "Automatic",
                "engine" => "6.2L V8",
                "maxSpeed" => 305,
                "horsepower" => 455,
                "seats" => 2,
                "fuelType" => "Petrol",
                "body_type_id" => 7,
                "category_id" => 7,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "F8 Tributo Spyder",
                "slug" => "ferrari-f8-tributo",
                "brand_id" => 8,
                "price" => 957.0,
                "year" => 2023,
                "color" => "Red",
                "zeroToHundred" => 3.2,
                "transmission" => "Automatic",
                "engine" => "V8 twin-turbo",
                "maxSpeed" => 320,
                "horsepower" => 710,
                "seats" => 2,
                "fuelType" => "Petrol",
                "body_type_id" => 7,
                "category_id" => 7,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Sport",
                "slug" => "range-rover-sport",
                "brand_id" => 10,
                "price" => 192.0,
                "year" => 2021,
                "color" => "Black",
                "zeroToHundred" => 7.2,
                "transmission" => "Automatic",
                "engine" => "3.0L V6",
                "maxSpeed" => 220,
                "horsepower" => 340,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 2,
                "category_id" => 5,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "CLA 250",
                "slug" => "mercedes-cla250",
                "brand_id" => 9,
                "price" => 141.0,
                "year" => 2024,
                "color" => "White",
                "zeroToHundred" => 6.9,
                "transmission" => "Automatic",
                "engine" => "2.0L 4 CYLINDERS",
                "maxSpeed" => 248,
                "horsepower" => 221,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 1,
                "category_id" => 6,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Panamera 4",
                "slug" => "porsche-panamera",
                "brand_id" => 11,
                "price" => 254.0,
                "year" => 2020,
                "color" => "Dark Grey",
                "zeroToHundred" => 5.8,
                "transmission" => "Automatic",
                "engine" => "3.6L V6",
                "maxSpeed" => 260,
                "horsepower" => 330,
                "seats" => 4,
                "fuelType" => "Petorl",
                "body_type_id" => 4,
                "category_id" => 6,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "Mustang",
                "slug" => "ford-mustang-classic",
                "brand_id" => 6,
                "price" => 1511.0,
                "year" => 1996,
                "color" => "Beige",
                "zeroToHundred" => 5.4,
                "transmission" => "Automatic",
                "engine" => "V8",
                "maxSpeed" => 181,
                "horsepower" => 310,
                "seats" => 4,
                "fuelType" => "Petrol",
                "body_type_id" => 1,
                "category_id" => 4,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "XF",
                "slug" => "jaguar-xf",
                "brand_id" => 5,
                "price" => 90.0,
                "year" => 2019,
                "color" => "Black",
                "zeroToHundred" => 8.3,
                "transmission" => "Automatic",
                "engine" => "3.0L V6",
                "maxSpeed" => 237,
                "horsepower" => 238,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 4,
                "category_id" => 5,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "EQS 580",
                "slug" => "mercedes-eqs",
                "brand_id" => 9,
                "price" => 217.0,
                "year" => 2023,
                "color" => "Black",
                "zeroToHundred" => 4.3,
                "transmission" => "Automatic",
                "engine" => "Electric motor type Dual Permanently Excited Synchronous (PSM)",
                "maxSpeed" => 210,
                "horsepower" => 536,
                "seats" => 4,
                "fuelType" => "Electric",
                "body_type_id" => 4,
                "category_id" => 3,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "C200",
                "slug" => "mercedes-c-class",
                "brand_id" => 9,
                "price" => 127.0,
                "year" => 2022,
                "color" => "Silver",
                "zeroToHundred" => 7.1,
                "transmission" => "Automatic",
                "engine" => "2.0L",
                "maxSpeed" => 245,
                "horsepower" => 204,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 4,
                "category_id" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "A4",
                "slug" => "audi-a4",
                "brand_id" => 3,
                "price" => 102.0,
                "year" => 2024,
                "color" => "Black",
                "zeroToHundred" => 5.6,
                "transmission" => "Automatic",
                "engine" => "4 cylinder, 2.5L",
                "maxSpeed" => 210,
                "horsepower" => 150,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 4,
                "category_id" => 8,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "318",
                "slug" => "bmw-3-series",
                "brand_id" => 2,
                "price" => 153.0,
                "year" => 2019,
                "color" => "White",
                "zeroToHundred" => 9.1,
                "transmission" => "Automatic",
                "engine" => "1.5L 4Cylinder",
                "maxSpeed" => 210,
                "horsepower" => 136,
                "seats" => 5,
                "fuelType" => "Petorl",
                "body_type_id" => 8,
                "category_id" => 8,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "RS6",
                "slug" => "audi-rs6",
                "brand_id" => 3,
                "price" => 357.0,
                "year" => 2022,
                "color" => "Grey",
                "zeroToHundred" => 3.6,
                "transmission" => "Automatic",
                "engine" => "4.0-liter V-8 TSSI Twin Turbo",
                "maxSpeed" => 250,
                "horsepower" => 621,
                "seats" => 4,
                "fuelType" => "Petrol",
                "body_type_id" => 6,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "F150",
                "slug" => "ford-f150",
                "brand_id" => 6,
                "price" => 230.0,
                "year" => 2016,
                "color" => "Black",
                "zeroToHundred" => 6.6,
                "transmission" => "Automatic",
                "engine" => "3.5L V6",
                "maxSpeed" => 180,
                "horsepower" => 375,
                "seats" => 5,
                "fuelType" => "Petrol",
                "body_type_id" => 5,
                "category_id" => 2,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "title" => "V250",
                "slug" => "mercedes-v-class",
                "brand_id" => 9,
                "price" => 230.0,
                "year" => 2023,
                "color" => "Black",
                "zeroToHundred" => 9.0,
                "transmission" => "Automatic",
                "engine" => "2.4L 4 cylinder",
                "maxSpeed" => 190,
                "horsepower" => 236,
                "seats" => 8,
                "fuelType" => "Petrol",
                "body_type_id" => 3,
                "category_id" => 5,
                "created_at" => now(),
                "updated_at" => now()
            ],
        ]);
    }
}
